### ISSUE TITLE
Cant use custom Axios Instance, due some type conflicts between cachios and axios

### ISSUE THREAD

**Issue by viniciuscasarin** [AlbinoDrought/cachios#75] opened 2022-08-01 03:26 UTC
I'm currently trying to implement the following code, wich is available in this doc https://github.com/AlbinoDrought/cachios#custom-axios-instance

```js const cachios = require('cachios');
const axios = require('axios');

const axiosInstance = axios.create({
  baseURL: 'https://jsonplaceholder.typicode.com',
});

// all requests will now use this axios instance
const cachiosInstance = cachios.create(axiosInstance);
```

But my code is throwing this error: 
`Argument of type 'import("*/node_modules/axios/index").AxiosInstance' is not assignable to parameter of type 'import("*/node_modules/cachios/node_modules/axios/index").AxiosInstance'. The types of 'defaults.headers.common' are incompatible between these types. Type 'import("*/node_modules/axios/index").AxiosRequestHeaders' is not assignable to type 'import("*/node_modules/cachios/node_modules/axios/index").AxiosRequestHeaders'. Index signatures are incompatible. Type 'string | number | boolean' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'.`

It seems that is happening a conflict between cachios and axios type.

The version of both libs in my package.json:
    "axios": "^0.27.2",
    "cachios": "^3.1.2",

**Comment by Barros42** [comment] 2022-08-03 02:20
Up!

**Comment by murylomf** [comment] 2022-08-03 02:33
I had the same problem here!

**Comment by mairascomparim** [comment] 2022-08-03 02:38
Same problem here :(

**Comment by AlbinoDrought** [comment] 2022-08-03 03:24
Hello, thank you for the reports.

Can you please try with `cachios@^3.1.3` to see if the issue is resolved?

`npm install --save cachios@^3.1.3`

Thanks!

**Comment by AlbinoDrought** [comment] 2022-08-03 04:00
Marking this as closed because I believe it's solved.

I added a sample Typescript project here: https://github.com/AlbinoDrought/cachios/tree/master/tests/integration/cachios-typescript

This project gets built against cachios and the latest version of axios here: https://github.com/AlbinoDrought/cachios/blob/master/.github/workflows/typescript-compat.yml

It currently succeeds: https://github.com/AlbinoDrought/cachios/runs/7644727470

**Closed by AlbinoDrought** 2022-08-03 04:00 UTC

**Comment by viniciuscasarin** [comment] 2022-08-03 15:21
@AlbinoDrought  It's working just fine, thanks for the good work!
